export type RootStackParamList = {
  Login: undefined;
  Register: { sponsorId?: string } | undefined;
  ConsumerHome: undefined;
  Delivery: undefined;
  NearbyStores: undefined;
  NearMe: undefined;
  Ads: undefined;
  Society: undefined;
  BusinessRegistration: undefined;
  ConsumerScanner: undefined;
  Cart: undefined;
  TriPay: undefined;
  TriEat: undefined;
  TriTrip: undefined;
  TriPickDrop: undefined;
  TriZone: undefined;
  TriInventoryBilling: undefined;
  Profile: undefined;
  ConsumerKYC: undefined;
  GiftCards: undefined;
  ShopDetails: { id: string; mode?: 'nearby-delivery'; lat?: number; lng?: number };
  ProductDetails: { id: string };
  StorePayment: { id: string };
  SecureCheckout: { id: string; amount?: number; onlineOrderId?: string };
  UpiPayment: { id: string; amount?: number; refId?: string; onlineOrderId?: string };
  MyOrders: undefined;
  Orders: undefined;
  OrderDetails: { id: string };
  TrackOrder: { id: string };
};
