CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sponsor_id VARCHAR(40),
  sponsor_name VARCHAR(160),
  full_name VARCHAR(160) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  email VARCHAR(180),
  pin_code VARCHAR(12),
  district VARCHAR(120),
  state VARCHAR(120),
  password_hash VARCHAR(120),
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  mobile_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_users_mobile UNIQUE (mobile),
  CONSTRAINT uk_users_email UNIQUE (email)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS sponsor_id VARCHAR(40);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sponsor_name VARCHAR(160);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_code VARCHAR(12);
ALTER TABLE users ADD COLUMN IF NOT EXISTS district VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(120);

CREATE TABLE IF NOT EXISTS otp_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile VARCHAR(20) NOT NULL,
  purpose VARCHAR(32) NOT NULL,
  otp_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP NULL,
  attempts INT NOT NULL DEFAULT 0,
  provider_message_id VARCHAR(120),
  provider_response TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_otp_mobile_purpose ON otp_requests (mobile, purpose, created_at);

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_sessions_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON user_sessions (user_id);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_admin_sessions_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_admin_sessions_username ON admin_sessions (username);

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL,
  password_hash VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_admins_username UNIQUE (username)
);

-- ============================================================
-- Hubble Gift Cards: raw webhook events (idempotent audit log)
-- Mirrors Django: business.HubbleWebhookEvent
-- ============================================================
CREATE TABLE IF NOT EXISTS hubble_webhook_events (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider                 VARCHAR(32)  NOT NULL DEFAULT 'hubble',
  event_type               VARCHAR(64)  NOT NULL DEFAULT '',
  transaction_reference_id VARCHAR(64)  NOT NULL DEFAULT '',
  order_status             VARCHAR(32)  NOT NULL DEFAULT '',
  idempotency_key          VARCHAR(255) NOT NULL,
  x_verify                 VARCHAR(256) NOT NULL DEFAULT '',
  raw_body                 TEXT         NOT NULL DEFAULT '',
  process_status           VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
  process_error            TEXT         NOT NULL DEFAULT '',
  received_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at             TIMESTAMP    NULL,
  CONSTRAINT uk_hubble_webhook_idem UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_hubble_webhook_event_type ON hubble_webhook_events (provider, event_type, received_at);
CREATE INDEX IF NOT EXISTS idx_hubble_webhook_tx_ref     ON hubble_webhook_events (transaction_reference_id, order_status);

-- ============================================================
-- Hubble Gift Cards: canonical transaction state
-- Mirrors Django: business.HubbleTransaction
-- ============================================================
CREATE TABLE IF NOT EXISTS hubble_transactions (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider                 VARCHAR(32)   NOT NULL DEFAULT 'hubble',
  transaction_reference_id VARCHAR(64)   NOT NULL,
  hubble_user_id           VARCHAR(128)  NOT NULL DEFAULT '',
  user_id                  BIGINT        NULL REFERENCES users(id) ON DELETE SET NULL,
  status                   VARCHAR(16)   NOT NULL DEFAULT 'UNKNOWN',
  amount                   NUMERIC(12,2) NULL,
  discount_amount          NUMERIC(12,2) NULL,
  currency                 VARCHAR(8)    NOT NULL DEFAULT '',
  last_webhook_event_id    BIGINT        NULL REFERENCES hubble_webhook_events(id) ON DELETE SET NULL,
  created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_webhook_received_at TIMESTAMP     NULL,
  CONSTRAINT uk_hubble_tx_ref UNIQUE (transaction_reference_id)
);

CREATE INDEX IF NOT EXISTS idx_hubble_tx_user_id   ON hubble_transactions (user_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_hubble_tx_hub_user  ON hubble_transactions (hubble_user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_hubble_tx_status    ON hubble_transactions (provider, status, updated_at);
