CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sponsor_id VARCHAR(40),
  sponsor_name VARCHAR(160),
  full_name VARCHAR(160) NOT NULL,
  country_code VARCHAR(8) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  email VARCHAR(180),
  pin_code VARCHAR(12),
  district VARCHAR(120),
  state VARCHAR(120),
  password_hash VARCHAR(120),
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  mobile_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_users_mobile UNIQUE (mobile),
  CONSTRAINT uk_users_email UNIQUE (email)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS sponsor_id VARCHAR(40);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sponsor_name VARCHAR(160);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_code VARCHAR(12);
ALTER TABLE users ADD COLUMN IF NOT EXISTS district VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(120);

CREATE TABLE IF NOT EXISTS otp_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile VARCHAR(20) NOT NULL,
  purpose VARCHAR(32) NOT NULL,
  otp_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP NULL,
  attempts INT NOT NULL DEFAULT 0,
  provider_message_id VARCHAR(120),
  provider_response TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_otp_mobile_purpose ON otp_requests (mobile, purpose, created_at);

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_sessions_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON user_sessions (user_id);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_admin_sessions_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_admin_sessions_username ON admin_sessions (username);

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL,
  password_hash VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_admins_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS kyc_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
  digilocker_id VARCHAR(255),
  access_token_encrypted TEXT,
  refresh_token_encrypted TEXT,
  name VARCHAR(255),
  dob VARCHAR(32),
  gender VARCHAR(16),
  email VARCHAR(255),
  mobile VARCHAR(32),
  address TEXT,
  photo TEXT,
  aadhaar_last4 VARCHAR(4),
  pan_number VARCHAR(16),
  issued_documents_json TEXT,
  state VARCHAR(255),
  remarks TEXT,
  verified_at TIMESTAMP,
  verified_by_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
